# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
document.addEventListener "turbolinks:load", ->
  bindTitle = ->
    changeTitle = ->
      title = document.getElementById('article_title').value
      document.title = title
    input = document.getElementById('article_title')
    input.addEventListener 'change', changeTitle
    input.addEventListener 'keyup', changeTitle


  if document.body.classList.contains 'articles', 'new' or
     document.body.classList.contains 'articles', 'edit'
    bindTitle()
    windify()


# ---
# generated by js2coffee 2.2.0
wind = null
steps = 2
duration = 15000
windify = ->
  wind = document.getElementById('wind')
  Object.defineProperty wind, 'alpha',
    get: ->
      HTMLElement::alpha = (a) ->
      current_color = getComputedStyle(this).getPropertyValue('color')
      match = /rgba?\((\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*(\d+[\.\d+]*))?\)/g.exec(current_color)
      return match[4] ? "1"
    set: (alpha) ->
      @style.color = "rgba(0,0,0,#{alpha})"

  wind.addEventListener 'keyup', ->
    wind.alpha = 1
    opacityInterval()
  opacityInterval()

interval = null
opacityInterval = ->
  step = duration / steps
  if interval?
    clearInterval interval
  interval = setInterval lowerOpacity, step

lowerOpacity = ->
  wind.alpha -= 1 / steps
  if wind.alpha <= 0
    wind.value = ''
    clearInterval interval


#windify = ->
#  wind = document.getElementById('wind')
#  wind.addEventListener 'keydown', (evt) ->
#    if (evt.altKey and evt.key == 'Alt') or
#       (evt.controlKey) or
#       (evt.metaKey) or
#       (evt.shiftKey and evt.key == 'Shift') or
#       evt.key == 'Enter' or
#       evt.key == 'Backspace' or
#       evt.key == 'ArrowUp' or evt.key == 'ArrowDown' or
#       evt.key == 'ArrowLeft' or evt.key == 'ArrowRight'
#      return
#    evt.preventDefault()
#    # if evt.key == 'Enter'
#    #   return pasteHtmlAtCaret('<div></div>')
#    res = document.execCommand('insertHTML', false, '<span id="new" class="letter">' + evt.key + '</span>')
#    el = document.getElementById 'new'
#    el.removeAttribute 'id'
#    fadeAway el, 30000, 5
#    # pasteHtmlAtCaret('<span contenteditable="false" class="letter">' + evt.key + '</span>')

#fadeAway = (el, duration, steps) ->
#  step = duration / steps
#  el.style.opacity = 1
#  fade = ->
#    el.style.opacity -= 1 / steps
#    opacityFloat = parseFloat(el.style.opacity)
#    if parseFloat(el.style.opacity) <= 0
#      return el.remove()
#    setTimeout fade, step
#  setTimeout fade, step

#pasteHtmlAtCaret = (html, selectPastedContent) ->
#  sel = undefined
#  range = undefined
#  if window.getSelection
#    # IE9 and non-IE
#    sel = window.getSelection()
#    if sel.getRangeAt and sel.rangeCount
#      range = sel.getRangeAt(0)
#      range.deleteContents()
#      # Range.createContextualFragment() would be useful here but is
#      # only relatively recently standardized and is not supported in
#      # some browsers (IE9, for one)
#      el = document.createElement('div')
#      el.innerHTML = html
#      child = el.firstChild
#      fn = ->
#        fadeAway child, 3000, 5
#        # anime
#        #  targets: child,
#        #  opacity: 0,
#        #  duration: 30000
#        #
#        # $(child).fadeTo 30000, 0, ->
#        #   child.remove()
#        #
#        # child.classList.add 'fading'
#        # child.addEventListener 'transitionend', ->
#        #   child.remove()
#      setTimeout fn, 100
#      frag = document.createDocumentFragment()
#      node = undefined
#      lastNode = undefined
#      while node = el.firstChild
#        lastNode = frag.appendChild(node)
#      firstNode = frag.firstChild
#      range.insertNode frag
#      # Preserve the selection
#      if lastNode
#        range = range.cloneRange()
#        range.setStartAfter lastNode
#        if selectPastedContent
#          range.setStartBefore firstNode
#        else
#          range.collapse true
#        sel.removeAllRanges()
#        sel.addRange range
#  else if (sel = document.selection) and sel.type != 'Control'
#    # IE < 9
#    originalRange = sel.createRange()
#    originalRange.collapse true
#    sel.createRange().pasteHTML html
#    if selectPastedContent
#      range = sel.createRange()
#      range.setEndPoint 'StartToStart', originalRange
#      range.select()
#  return

# ---
# generated by js2coffee 2.2.0
